# -*- coding: utf-8 -*-
"""cnv_mmrf-commpass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/tiagochavo87/99f6bc018d1ed5c1e53ad684e3870a96/cnv_mmrf-commpass.ipynb
"""

# -*- coding: utf-8 -*-
"""CNV_MMRF-COMMPASS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBkMWqltr6p8Y51q2maan-JVs6MKIT1a
"""

import requests
import json
import os
import sys

# Parameters
GDC_API_URL = "https://api.gdc.cancer.gov/files"
PROJECT_ID = "MMRF-COMMPASS"
DATA_CATEGORY = "Copy Number Variation"

DOWNLOAD_DIR = "mmrf_cnv_data"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# Filter for public CNV files of the project
# Filtro para arquivos CNV públicos do projeto
filters = {
    "op": "and",
    "content": [
        {"op": "=", "content": {"field": "cases.project.project_id", "value": [PROJECT_ID]}},
        {"op": "=", "content": {"field": "data_category", "value": [DATA_CATEGORY]}},
        {"op": "in", "content": {"field": "access", "value": ["open"]}}  # only public files
    ]
}

params = {
    "filters": json.dumps(filters),
    "fields": "file_id,file_name,data_format,file_size",
    "format": "JSON",
    "size": 1000
}

print(f"Listing public CNV files for project {PROJECT_ID}...")

# Send request to GDC API to list files
# Envia requisição para a API do GDC para listar arquivos
response = requests.post(GDC_API_URL, headers={"Content-Type": "application/json"}, data=json.dumps(params))
response.raise_for_status()
res_json = response.json()

files = res_json['data']['hits']
num_files = len(files)
print(f"Found {num_files} public CNV files.")

if num_files == 0:
    print("No public CNV files found. Check access or filters.")
    sys.exit(0)

# Function to download an individual file
# Função para baixar arquivo individual
def download_file(file_id, file_name):
    url = f"https://api.gdc.cancer.gov/data/{file_id}"
    out_path = os.path.join(DOWNLOAD_DIR, file_name)
    print(f"Downloading {file_name} ({out_path})")
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

# Download all public files found
# Baixar todos os arquivos públicos encontrados
for f in files:
    download_file(f['file_id'], f['file_name'])

print(f"Download complete! Files are in {DOWNLOAD_DIR}/")
print(f"To list the downloaded files, run: !ls -lh {DOWNLOAD_DIR}")

# --- End of first block ---

# --- Second block: Listing and downloading files with pagination ---
import requests
import json
import os
import sys

# Main Parameters
# Parâmetros principais
GDC_API_URL = "https://api.gdc.cancer.gov/files"
PROJECT_ID = "MMRF-COMMPASS"
DATA_CATEGORY = "Copy Number Variation"
DOWNLOAD_DIR = "mmrf_cnv_data"

os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# Filter for public CNV files of the project
# Filtro para arquivos públicos CNV do projeto
base_filter = {
    "op": "and",
    "content": [
        {"op": "=", "content": {"field": "cases.project.project_id", "value": [PROJECT_ID]}},
        {"op": "=", "content": {"field": "data_category", "value": [DATA_CATEGORY]}},
        {"op": "in", "content": {"field": "access", "value": ["open"]}}  # Only public files
    ]
}

size_per_page = 1000
from_offset = 0
all_files = []

print(f"Listing public CNV files for project {PROJECT_ID} using pagination...")

# Loop to paginate through GDC API results
# Loop para paginar os resultados da API do GDC
while True:
    params = {
        "filters": json.dumps(base_filter),
        "fields": "file_id,file_name,data_format,file_size",
        "format": "JSON",
        "size": size_per_page,
        "from": from_offset
    }

    response = requests.post(GDC_API_URL, headers={"Content-Type": "application/json"}, data=json.dumps(params))
    response.raise_for_status()
    res_json = response.json()

    files = res_json['data']['hits']
    if not files:
        break

    all_files.extend(files)
    print(f"Page with {len(files)} files listed... Total accumulated: {len(all_files)}")

    if len(files) < size_per_page:
        break

    from_offset += size_per_page

if not all_files:
    print("No public CNV files found.")
    sys.exit(0)

print(f"Total public CNV files found: {len(all_files)}")

# Function to download an individual file
# Função para baixar arquivo individualmente
def download_file(file_id, file_name):
    out_path = os.path.join(DOWNLOAD_DIR, file_name)
    if os.path.exists(out_path):
        print(f"File already exists. Skipping: {file_name}")
        return
    url = f"https://api.gdc.cancer.gov/data/{file_id}"
    print(f"Downloading {file_name} ...")
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

print("\nStarting file download...")

# Download all files found
# Baixar todos os arquivos encontrados
for file in all_files:
    download_file(file['file_id'], file['file_name'])

print(f"\nDownload complete! Files saved in: {DOWNLOAD_DIR}/")
print(f"To list the downloaded files, run:\n!ls -lh {DOWNLOAD_DIR}")

# --- End of second block ---

# --- Third block: Listing and downloading files with refined pagination and existence check ---
import requests
import json
import os
import sys

# Main Parameters
# Parâmetros principais
GDC_API_URL = "https://api.gdc.cancer.gov/files"
PROJECT_ID = "MMRF-COMMPASS"
DATA_CATEGORY = "Copy Number Variation"
DOWNLOAD_DIR = "mmrf_cnv_data"

# Create download folder if it doesn't exist
# Cria pasta para download, se ainda não existir
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# Filter to search for public CNV files
# Filtro para buscar arquivos públicos CNV
base_filter = {
    "op": "and",
    "content": [
        {"op": "=", "content": {"field": "cases.project.project_id", "value": [PROJECT_ID]}},
        {"op": "=", "content": {"field": "data_category", "value": [DATA_CATEGORY]}},
        {"op": "in", "content": {"field": "access", "value": ["open"]}}
    ]
}

size_per_page = 2000
from_offset = 0
all_files = []

print(f"Listing public CNV files for project {PROJECT_ID} with pagination...")

# Loop to paginate through GDC API results
# Loop para paginar os resultados da API do GDC
while True:
    params = {
        "filters": json.dumps(base_filter),
        "fields": "file_id,file_name,data_format,file_size",
        "format": "JSON",
        "size": size_per_page,
        "from": from_offset
    }

    response = requests.post(GDC_API_URL, headers={"Content-Type": "application/json"}, data=json.dumps(params))
    response.raise_for_status()
    res_json = response.json()

    files = res_json['data']['hits']
    if not files:
        break

    all_files.extend(files)
    print(f"Page with {len(files)} files listed. Total accumulated: {len(all_files)}")

    if len(files) < size_per_page:
        break

    from_offset += size_per_page

if not all_files:
    print("No public CNV files found.")
    sys.exit(0)

print(f"Total public CNV files found: {len(all_files)}")

# Function to download file only if it doesn't exist
# Função para baixar arquivo apenas se não existir
def download_file_if_new(file_id, file_name):
    out_path = os.path.join(DOWNLOAD_DIR, file_name)
    if os.path.exists(out_path):
        print(f"File already exists, skipping: {file_name}")
        return
    url = f"https://api.gdc.cancer.gov/data/{file_id}"
    print(f"Downloading new file: {file_name} ...")
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

print("\nStarting download of new files...")

# Download all files found, skipping existing ones
# Baixar todos os arquivos encontrados, pulando os existentes
for file in all_files:
    download_file_if_new(file['file_id'], file['file_name'])

print(f"\nDownload complete! Files saved in: {DOWNLOAD_DIR}/")
print(f"To list the downloaded files:\n!ls -lh {DOWNLOAD_DIR}")

# --- End of third block ---

# --- Fourth block: Generating GDC Manifest and using gdc-client for download ---
import requests
import json
import os
import sys

# Parameters
# Parâmetros
GDC_API_URL = "https://api.gdc.cancer.gov/files"
PROJECT_ID = "MMRF-COMMPASS"
DATA_CATEGORY = "Copy Number Variation"
MANIFEST_FILENAME = "gdc_manifest_mmrf_cnv.txt"
DOWNLOAD_DIR = "mmrf_cnv_data"

os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# Filter to generate the list/manifest of public CNV files for the project
# Filtro para gerar a lista/manifesto dos arquivos CNV públicos do projeto
filters = {
    "op": "and",
    "content": [
        {"op": "=", "content": {"field": "cases.project.project_id", "value": [PROJECT_ID]}},
        {"op": "=", "content": {"field": "data_category", "value": [DATA_CATEGORY]}},
        {"op": "in", "content": {"field": "access", "value": ["open"]}}
    ]
}

params = {
    "filters": json.dumps(filters),
    "fields": "file_id,file_name",
    "format": "tsv",
    "size": 100000
}

print(f"Generating manifest for CNV files of project {PROJECT_ID}...")

try:
    # Request to GDC API to generate manifest file (TSV format)
    # Requisição à API do GDC para gerar o arquivo manifesto (formato TSV)
    response = requests.post(GDC_API_URL, headers={"Content-Type": "application/json"}, data=json.dumps(params))
    response.raise_for_status()

    with open(MANIFEST_FILENAME, "w") as f:
        f.write(response.text)

    num_files = len(response.text.strip().split('\n')) - 1
    if num_files > 0:
        print(f"Manifest generated: {MANIFEST_FILENAME}")
        print(f"Number of files to download: {num_files}")
    else:
        print("No files found with the specified filters.")
        sys.exit(0)

except requests.exceptions.RequestException as e:
    print(f"Error accessing GDC API: {e}")
    sys.exit(1)

# Installation of GDC Data Transfer Tool
# Instalação do GDC Data Transfer Tool
print("\nInstalling GDC Data Transfer Tool...")

# Shell commands to download and install gdc-client
# Comandos shell para baixar e instalar o gdc-client
!wget https://gdc.cancer.gov/system/files/docs/gdc-client/gdc-client_v1.7.0_Linux_x64.zip -q
!unzip -o gdc-client_v1.7.0_Linux_x64.zip
!chmod +x gdc-client

# Download files using the manifest and gdc-client
# Download dos arquivos pelo manifesto e gdc-client
print(f"\nStarting file download in folder: {DOWNLOAD_DIR}")

!./gdc-client download -m {MANIFEST_FILENAME} -d {DOWNLOAD_DIR}

print("\nDownload complete!")
print(f"Files available in: {DOWNLOAD_DIR}/")
print(f"To list the files, run:\n!ls -lh {DOWNLOAD_DIR}")

# Shell command to list downloaded files
# Comando shell para listar os arquivos baixados
!ls -lh mmrf_cnv_data

# Shell command to zip the folder
# Comando shell para compactar a pasta
!zip -r mmrf_cnv_data.zip mmrf_cnv_data

from google.colab import files
# Download the zip file to your computer (Colab specific)
# Baixar o arquivo zip para seu computador (Específico do Colab)
files.download("mmrf_cnv_data.zip")

# --- End of fourth block ---

# --- Fifth block: Combining CNV files (simple .seg) ---
import os

folder = "mmrf_cnv_data"
output_file = "combined_cnvs.seg"

# List .seg files in the folder
# Lista arquivos .seg na pasta
files = [f for f in os.listdir(folder) if f.endswith(".seg")]
print(f"Files found to combine: {len(files)}")

# Combine files, writing header only from the first file
# Combina arquivos, escrevendo cabeçalho apenas do primeiro arquivo
with open(output_file, "w") as outfile:
    for i, filename in enumerate(files):
        path = os.path.join(folder, filename)
        with open(path, "r") as infile:
            lines = infile.readlines()
            # Write header only from the first file
            # Escreve cabeçalho só do primeiro arquivo
            if i == 0:
                outfile.writelines(lines)
            else:
                # Write only lines after the first one (second line onwards)
                # Escreve somente linhas depois da primeira (segunda linha em diante)
                outfile.writelines(lines[1:])

print(f"Combined file created: {output_file}")

# Quick verification of the first lines
# Verificação rápida das primeiras linhas
with open(output_file) as f:
    for _ in range(10):
        print(f.readline().strip())

# --- End of fifth block ---

"""# New Section"""

# --- Sixth block: Combining CNV files into TXT, CSV, and SEG formats ---
import os

folder = "mmrf_cnv_data"

output_txt = "combined_cnvs.txt"
output_csv = "combined_cnvs.csv"
output_seg = "combined_cnvs.seg"

# List files with .seg or .seg.txt extension
# Lista arquivos com extensão .seg ou .seg.txt
files = [f for f in os.listdir(folder) if f.endswith(".seg") or f.endswith(".seg.txt")]
print(f"Files found to combine: {len(files)}")

# Function to convert a tab-separated line to CSV (comma-separated)
# Função para converter uma linha tabulada para CSV (separada por vírgula)
def to_csv_line(line):
    return ','.join(line.strip().split('\t')) + '\n'

# Function to read non-empty lines from a file
# Função para ler linhas não vazias de um arquivo
def read_non_empty_lines(path):
    with open(path, "r") as f:
        # Remove empty lines or lines with only whitespace
        # Remove linhas vazias ou com espaços em branco
        lines = [line for line in f if line.strip()]
    return lines

# Combine files into three different formats
# Combina arquivos em três formatos diferentes
with open(output_txt, "w") as out_txt, open(output_csv, "w") as out_csv, open(output_seg, "w") as out_seg:
    for i, filename in enumerate(files):
        path = os.path.join(folder, filename)
        lines = read_non_empty_lines(path)
        print(f"Reading file {filename} with {len(lines)} non-empty lines.")

        if not lines:
            print(f"Warning: file {filename} is empty or only has blank lines, skipping.")
            continue

        # Pure TXT and SEG: maintains tabs, includes header only once
        # TXT puro e SEG: mantém tabs, inclui cabeçalho só 1x
        if i == 0:
            out_txt.writelines(lines)
            out_seg.writelines(lines)
        else:
            out_txt.writelines(lines[1:])
            out_seg.writelines(lines[1:])

        # CSV converts tabs to commas
        # CSV converte tabs em vírgulas
        if i == 0:
            out_csv.write(to_csv_line(lines[0]))
        out_csv.writelines([to_csv_line(l) for l in lines[1:]])

print(f"Combination complete: files saved as {output_txt}, {output_csv}, {output_seg}")

print("\nExample of the first lines of the combined CSV file:")
with open(output_csv, "r") as f:
    for _ in range(10):
        print(f.readline().strip())

# --- End of sixth block ---

# --- Seventh block: Estimating the number of distinct samples ---
import os
import pandas as pd

folder = "mmrf_cnv_data"
sample_ids = set()

# List files containing CNVs
# Lista arquivos que contêm os CNVs
files = [f for f in os.listdir(folder) if f.endswith(".seg") or f.endswith(".seg.txt")]

# Iterate through files to extract sample IDs
# Itera sobre os arquivos para extrair IDs de amostra
for filename in files:
    path = os.path.join(folder, filename)
    df = pd.read_csv(path, sep="\t")  # reading as tab-separated

    # Check column names to identify where the sample ID is located
    # Verificar nomes das colunas para identificar onde está o ID da amostra
    print(f"Columns in {filename}: {list(df.columns)}")

    # Common attempt: 'Sample' or 'SampleID' or 'Sample_Name' column
    # Tentativa comum: coluna 'Sample' ou 'SampleID' ou 'Sample_Name'
    if 'Sample' in df.columns:
        sample_ids.update(df['Sample'].unique())
    elif 'SampleID' in df.columns:
        sample_ids.update(df['SampleID'].unique())
    elif 'Sample_Name' in df.columns:
        sample_ids.update(df['Sample_Name'].unique())
    else:
        # If not found, the filename can be used as an identifier
        # Se não encontrar, pode usar o nome do arquivo como identificador
        sample_ids.add(filename)

print(f"Estimated number of different samples: {len(sample_ids)}")

# --- End of seventh block ---

# --- Eighth block: Simple CNV classification based on Segment_Mean ---
import pandas as pd

# Input and output file
# Arquivo de entrada e saída
input_file = "combined_cnvs.txt"
output_file = "combined_cnvs_classified.txt"

# Read the combined file (tab-separated)
# Lê o arquivo combinado (tabulado)
df = pd.read_csv(input_file, sep='\t')

# Function to classify CNV based on Segment_Mean
# Função para classificar CNV com base em Segment_Mean
def classify_cnv(segment_mean):
    if segment_mean <= -1.5:
        return "Homozygous Deletion (0 copies)" # Deleção homozigota (0 cópias)
    elif -1.5 < segment_mean <= -0.3:
        return "Heterozygous Deletion (1 copy)" # Deleção heterozigota (1 cópia)
    elif -0.3 < segment_mean < 0.3:
        return "Diploid (2 copies)" # Diploide (2 cópias)
    elif 0.3 <= segment_mean < 0.9:
        return "Duplication (3 copies)" # Duplicação (3 cópias)
    elif segment_mean >= 0.9:
        return "Multiplication (>3 copies)" # Multiplicação (>3 cópias)
    else:
        return "Undefined" # Indefinido

# Apply classification to the DataFrame
# Aplica classificação ao DataFrame
df['CNV_Type'] = df['Segment_Mean'].apply(classify_cnv)

# Save the result to a tab-separated TXT file
# Salva o resultado em arquivo TXT tabulado
df.to_csv(output_file, sep='\t', index=False)

print(f"Classified file saved as {output_file}")

# Quick example of the first lines
# Exemplo rápido das primeiras linhas
print(df.head())

# --- End of eighth block ---

# --- Ninth block: Detailed CNV classification based on refined thresholds ---
import pandas as pd

# 1. Refined Thresholds (Based on Theoretical Values)
# 1. Limiares Refinados (Baseados nos Valores Teóricos)
# Remember: These are approximate thresholds for real cancer samples.
# Lembre-se: Estes são limiares aproximados para amostras de câncer real.

# Loss
# Perda
LIMIAR_PERDA_HOMOZIGOTA = -1.5 # < -1.5 (Below theoretical -1.0, for more safety)
LIMIAR_PERDA_1_COPIA = -0.5    # Between -1.5 and -0.5 (Around theoretical -1.0)

# Neutral
# Neutro
LIMIAR_NEUTRO_MAX = 0.2
LIMIAR_NEUTRO_MIN = -0.2

# Gain
# Ganho
LIMIAR_GANHO_2_COPIAS = 0.8    # > 0.8 (Around theoretical 1.0)
LIMIAR_GANHO_1_COPIA = 0.3     # Between 0.3 and 0.8 (Around theoretical 0.58)


# 2. Detailed Classification Function
# 2. Função de Classificação Detalhada
def classificar_cnv_detalhada(segment_mean):
    """Classifies the CNV type into 6 categories based on Segment_Mean."""
    # "Classifica o tipo de CNV em 6 categorias com base em Segment_Mean."
    if segment_mean <= LIMIAR_PERDA_HOMOZIGOTA:
        return 'Homozygous Deletion (0 Copies)' # 'Deleção Homozigota (0 Copias)'
    elif segment_mean <= LIMIAR_PERDA_1_COPIA:
        return '1-Copy Loss (1 Copy)' # 'Deleção de 1 Cópia (1 Cópia)'

    elif segment_mean >= LIMIAR_GANHO_2_COPIAS:
        return '2+ Copy Gain (4+ Copies)' # 'Ganho de 2+ Cópias (4+ Cópias)'
    elif segment_mean >= LIMIAR_GANHO_1_COPIA:
        return '1-Copy Gain (3 Copies)' # 'Ganho de 1 Cópia (3 Cópias)'

    elif (segment_mean > LIMIAR_NEUTRO_MIN) and (segment_mean < LIMIAR_NEUTRO_MAX):
        return 'Neutral Copy (2 Copies)' # 'Cópia Neutra (2 Cópias)'
    else:
        # Segments between the neutral zone and clearer Gain/Loss thresholds.
        # Segmentos entre a zona neutra e os limiares de Ganho/Perda mais claros.
        return 'Undetermined' # 'Indeterminado'

# --- Application to DataFrame (Assuming combined_cnvs.txt is available) ---
# --- Aplicação ao DataFrame (Se o arquivo for combinado_cnvs.txt) ---

# Load the file (Repetition of the first part, assuming the same file)
# Carregar o arquivo (Repetição da primeira parte, assumindo o mesmo arquivo)
try:
    df = pd.read_csv("combined_cnvs.txt", sep='\t')
except:
    print("Error loading file. Using example data for demonstration.")
    # "Erro ao carregar o arquivo. Usando dados de exemplo para demonstração."
    # Example data for demonstration
    # Exemplo de dados para demonstração
    data = {'Segment_Mean': [-1.1, -0.6, -0.1, 0.05, 0.6, 1.2, -2.5, 0.3]}
    df = pd.DataFrame(data)

if 'Segment_Mean' in df.columns:
    df['CNV_Type_Detalhada'] = df['Segment_Mean'].apply(classificar_cnv_detalhada)

    # Save the result (For demonstration purposes only)
    # Salvar o resultado (Apenas para fins de demonstração)
    output_filename_detalhado = "combined_cnvs_classificado_detalhado.txt"
    df.to_csv(output_filename_detalhado, sep='\t', index=False)

    print(f"\n--- Detailed Classification Complete ---")
    print(f"The new file '{output_filename_detalhado}' includes the column 'CNV_Type_Detalhada'.")
    print(df[['Segment_Mean', 'CNV_Type_Detalhada']].head())
    print("\nWARNING: This classification is based on ideal theoretical values. For high precision in tumor samples, Purity and Ploidy columns are needed.")
    # print("\nAVISO: Esta classificação é baseada em valores teóricos ideais. Para alta precisão em amostras de tumor, são necessárias colunas de Pureza e Plodía.")
else:
    print("Error: The column 'Segment_Mean' was not found. Adjust the column name.")
    # "Erro: A coluna 'Segment_Mean' não foi encontrada. Ajuste o nome da coluna."

# --- End of ninth block ---

# --- Tenth block: Analyzing CNV segment frequency and characterization (Simple classification) ---
import pandas as pd

input_file = "combined_cnvs_classified.txt"  # classified file, with CNV_Type
# arquivo classificado, com CNV_Type

df = pd.read_csv(input_file, sep='\t')

# Check if the CNV_Type column exists
# Verifica se a coluna CNV_Type existe
if 'CNV_Type' not in df.columns:
    print("Column 'CNV_Type' not found in the file. Please use the classified file.")
    # "Column 'CNV_Type' não encontrada no arquivo. Por favor, use o arquivo classificado."
else:
    # Create SegmentID column by concatenating coordinates
    # Cria coluna SegmentID com concatenação das coordenadas
    df['SegmentID'] = df['Chromosome'].astype(str) + ":" + df['Start'].astype(str) + "-" + df['End'].astype(str)

    # Count occurrences grouping by SegmentID and CNV_Type
    # Conta ocorrências agrupando por SegmentID e CNV_Type
    segment_counts = df.groupby(['SegmentID', 'CNV_Type']).size().reset_index(name='Count')

    total_counts = segment_counts['Count'].sum()
    segment_counts['Frequency'] = segment_counts['Count'] / total_counts

    # Function to characterize CNV
    # Função para caracterizar CNV
    def characterize_cnv(cnv_type):
        if 'homozygous deletion' in cnv_type.lower() or 'deleção homozigota' in cnv_type.lower():
            return "Complete loss of genetic material" # "Perda completa de material genético"
        elif 'heterozygous deletion' in cnv_type.lower() or 'deleção heterozigótica' in cnv_type.lower():
            return "Partial loss of genetic material" # "Perda parcial de material genético"
        elif 'neutral' in cnv_type.lower() or 'neutro' in cnv_type.lower():
            return "No significant alteration" # "Sem alteração significativa"
        elif 'gain' in cnv_type.lower() or 'ganho' in cnv_type.lower():
            return "Duplication or slight amplification" # "Duplicação ou amplificação leve"
        elif 'amplification' in cnv_type.lower():
            return "High amplification, multiple copies" # "Amplificação alta, múltiplas cópias"
        else:
            return "Unknown type" # "Tipo desconhecido"

    segment_counts['Characterization'] = segment_counts['CNV_Type'].apply(characterize_cnv)

    # Display the top 5 most frequent CNVs
    # Exibe as 5 CNVs mais frequentes
    top5_cnvs = segment_counts.sort_values(by='Count', ascending=False).head(5)
    print("The 5 most frequent CNVs in the sample:")
    # "As 5 CNVs mais frequentes na amostra:"
    print(top5_cnvs[['SegmentID', 'Count', 'Frequency', 'CNV_Type', 'Characterization']])

# --- End of tenth block ---

# --- Eleventh block: Generating frequency report with placeholder for gnomAD query (Simple classification) ---
import pandas as pd
import requests

input_file = "combined_cnvs_classified.txt"
report_file = "cnv_frequency_report.txt"

# Read classified data
# Ler dados classificados
df = pd.read_csv(input_file, sep='\t')

# Create unique segment identifier
# Criar identificador único do segmento
df['SegmentID'] = df['Chromosome'].astype(str) + ":" + df['Start'].astype(str) + "-" + df['End'].astype(str)

# Count occurrence and calculate frequency in %
# Contar ocorrência e calcular frequência em %
segment_counts = df.groupby(['SegmentID', 'CNV_Type']).size().reset_index(name='Count')
total = segment_counts['Count'].sum()
segment_counts['Frequency_pct'] = (segment_counts['Count'] / total) * 100

# Select the 5 most frequent CNVs
# Selecionar as 5 CNVs mais frequentes
top5 = segment_counts.sort_values('Count', ascending=False).head(5)

# Placeholder function for querying gnomAD CNV frequency
# Função placeholder para consulta de frequência CNV no gnomAD
def query_gnomad_cnv_chrom_region(chrom, start, end):
    # Example gnomAD CNV endpoint - adjust if specific API needed
    # Exemplo de endpoint para CNV no gnomAD - ajustar se precisar API específica
    # This call is illustrative, the actual API may vary
    # Esta chamada é ilustrativa, a real API pode variar
    url = f"https://gnomad.broadinstitute.org/api"
    # Here, a GraphQL query would need to be built and sent, simplified example:
    # Aqui precisaria montar query GraphQL e enviar, exemplo simplificado:
    # Will return estimated frequency or None if unavailable
    # Retornará frequência estimada ou None se não disponível
    return None  # Placeholder for focusing on the logic

# Build report
# Montar relatório
with open(report_file, "w") as f:
    f.write("Report of most frequent CNVs in the cohort and frequencies in unaffected database\n\n")
    # "Relatório de CNVs mais frequentes na coorte e frequências em banco não afetado\n\n"
    f.write("SegmentID\tCNV Type\tCohort Frequency (%)\tUnaffected Database Frequency (%)\tCharacterization\n")
    # "SegmentID\tTipo CNV\tFrequência na coorte (%)\tFrequência em banco não afetado (%)\tCaracterização\n"

    for index, row in top5.iterrows():
        chrom = row['SegmentID'].split(':')[0]
        positions = row['SegmentID'].split(':')[1].split('-')
        start, end = positions[0], positions[1]

        freq_coorte = round(row['Frequency_pct'], 2)
        cnv_type = row['CNV_Type']
        # Example of simple characterization
        # Exemplo de caracterização simples
        if 'deletion' in cnv_type.lower() or 'deleção' in cnv_type.lower():
            characterization = "Loss of copies" # "Perda de cópias"
        elif 'gain' in cnv_type.lower() or 'amplification' in cnv_type.lower() or 'ganho' in cnv_type.lower():
            characterization = "Gain of copies" # "Ganho de cópias"
        else:
            characterization = "Unknown alteration" # "Alteração desconhecida"

        freq_pop = query_gnomad_cnv_chrom_region(chrom, start, end)
        freq_pop_str = f"{freq_pop}%" if freq_pop is not None else "Data not available" # "Dados não disponíveis"

        f.write(f"{row['SegmentID']}\t{cnv_type}\t{freq_coorte}\t{freq_pop_str}\t{characterization}\n")

print(f"Report saved to {report_file}")

# --- End of eleventh block ---

# --- Twelfth block: Generating frequency report (Detailed classification) ---
import pandas as pd

input_file = "combined_cnvs_classificado_detalhado.txt"
report_file = "cnv_frequency_report2.txt"

df = pd.read_csv(input_file, sep='\t')

# Ignore mitochondrial chromosome
# Ignorar cromossomo mitocondrial
df = df[~df['Chromosome'].isin(['chrM', 'MT', 'M'])]

# Create unique segment identifier
# Criar identificador único do segmento
df['SegmentID'] = df['Chromosome'].astype(str) + ":" + df['Start'].astype(str) + "-" + df['End'].astype(str)

# Use the correct column name for the detailed classification
# Use o nome correto da coluna da classificação detalhada
cnv_col = 'CNV_Type_Detalhada'

# Group to count occurrences and calculate frequencies
# Agrupar para contar ocorrências e calcular frequências
segment_counts = df.groupby(['SegmentID', cnv_col]).size().reset_index(name='Count')
total = segment_counts['Count'].sum()
segment_counts['Frequency_pct'] = (segment_counts['Count'] / total) * 100

# Select the top 5 most frequent CNVs
# Selecionar as 5 CNVs mais frequentes
top5 = segment_counts.sort_values('Count', ascending=False).head(5)

# Placeholder function for querying normative public databases
# Placeholder para consulta em bancos normativos (gnomAD, DGV)
def query_cnv_frequency_public_db(chrom, start, end):
    # Placeholder for querying normative databases (gnomAD, DGV)
    # Placeholder para consulta em bancos normativos (gnomAD, DGV)
    return "N/A" # "N/D"

# Function to characterize CNV based on detailed type
# Função para caracterizar CNV
def characterize_cnv(cnv_type):
    cnv_type_lower = cnv_type.lower()
    if 'homozygous deletion' in cnv_type_lower or 'deleção homozigota' in cnv_type_lower:
        return "Complete loss of genetic material" # "Perda completa de material genético"
    elif 'deletion' in cnv_type_lower or 'deleção' in cnv_type_lower:
        return "Partial loss of genetic material" # "Perda parcial de material genético"
    elif 'neutral' in cnv_type_lower or 'neutra' in cnv_type_lower:
        return "No significant alteration" # "Sem alteração significativa"
    elif 'gain' in cnv_type_lower or 'duplication' in cnv_type_lower or 'amplification' in cnv_type_lower:
        return "Copy gain or amplification" # "Ganho de cópias ou amplificação"
    else:
        return "Unknown type" # "Tipo desconhecido"

# Write the report
# Escrever o relatório
with open(report_file, "w") as f:
    f.write("Report of most frequent CNVs in the cohort and frequencies in normative (unaffected) database\n\n")
    # "Relatório de CNVs mais frequentes na coorte e frequências em banco de dados normativo (não afetado)\n\n"
    f.write("SegmentID\tCNV Type\tCohort Frequency (%)\tNormative Database Frequency (%)\tCharacterization\n")
    # "SegmentID\tTipo CNV\tFrequência na coorte (%)\tFrequência banco normativo (%)\tCaracterização\n"
    for idx, row in top5.iterrows():
        chrom = row['SegmentID'].split(':')[0]
        start, end = row['SegmentID'].split(':')[1].split('-')
        freq_coorte = round(row['Frequency_pct'], 2)
        cnv_type = row[cnv_col]
        freq_pop = query_cnv_frequency_public_db(chrom, start, end)
        characterization = characterize_cnv(cnv_type)
        f.write(f"{row['SegmentID']}\t{cnv_type}\t{freq_coorte}\t{freq_pop}\t{characterization}\n")

print(f"Report generated: {report_file}")

# --- End of twelfth block ---

# --- Thirteenth block: Generating frequency report with Count and detailed classification ---
import pandas as pd

input_file = "combined_cnvs_classificado_detalhado.txt"
report_file = "cnv_frequency_report3.txt"

df = pd.read_csv(input_file, sep='\t')

# Ignore mitochondrial chromosome
# Ignorar cromossomo mitocondrial
df = df[~df['Chromosome'].isin(['chrM', 'MT', 'M'])]

# Create unique segment identifier
# Criar identificador único do segmento
df['SegmentID'] = df['Chromosome'].astype(str) + ":" + df['Start'].astype(str) + "-" + df['End'].astype(str)

cnv_col = 'CNV_Type_Detalhada'

# Group to count occurrences and calculate frequencies
# Agrupar para contar ocorrências e calcular frequências
segment_counts = df.groupby(['SegmentID', cnv_col]).size().reset_index(name='Count')
total_samples = segment_counts['Count'].sum()
segment_counts['Frequency_pct'] = (segment_counts['Count'] / total_samples) * 100

# Select the top 5 most frequent CNVs
# Selecionar as 5 CNVs mais frequentes
top5 = segment_counts.sort_values('Count', ascending=False).head(5)

# Placeholder function for querying normative public databases
# Placeholder para consulta em bancos como gnomAD/DGV
def query_cnv_frequency_public_db(chrom, start, end):
    # Placeholder for querying normative databases (gnomAD/DGV)
    # Placeholder para consulta em bancos como gnomAD/DGV
    return "N/A" # "N/D"

# Function to characterize CNV based on detailed type
# Função para caracterizar CNV
def characterize_cnv(cnv_type):
    cnv_type_lower = cnv_type.lower()
    if 'homozygous deletion' in cnv_type_lower or 'deleção homozigota' in cnv_type_lower:
        return "Complete loss of genetic material" # "Perda completa de material genético"
    elif 'deletion' in cnv_type_lower or 'deleção' in cnv_type_lower:
        return "Partial loss of genetic material" # "Perda parcial de material genético"
    elif 'neutral' in cnv_type_lower or 'neutra' in cnv_type_lower:
        return "No significant alteration" # "Sem alteração significativa"
    elif 'gain' in cnv_col or 'duplication' in cnv_type_lower or 'amplification' in cnv_type_lower:
        return "Copy gain or amplification" # "Ganho de cópias ou amplificação"
    else:
        return "Unknown type" # "Tipo desconhecido"

# Write the report
# Escrever o relatório
with open(report_file, "w") as f:
    f.write("Report of most frequent CNVs in the cohort and frequencies in unaffected normative database\n\n")
    # "Relatório de CNVs mais frequentes na coorte e frequências em banco normativo não afetado\n\n"
    f.write("SegmentID\tCNV Type\tCohort Count\tCohort Frequency (%)\tNormative Database Frequency (%)\tCharacterization\n")
    # "SegmentID\tTipo CNV\tQuantidade na coorte\tFrequência na coorte (%)\tFrequência banco normativo (%)\tCaracterização\n"
    for idx, row in top5.iterrows():
        chrom = row['SegmentID'].split(':')[0]
        start, end = row['SegmentID'].split(':')[1].split('-')
        freq_coorte = round(row['Frequency_pct'], 2)
        cnv_type = row[cnv_col]
        count_coorte = row['Count']
        freq_pop = query_cnv_frequency_public_db(chrom, start, end)
        characterization = characterize_cnv(cnv_type)
        f.write(f"{row['SegmentID']}\t{cnv_type}\t{count_coorte}\t{freq_coorte}\t{freq_pop}\t{characterization}\n")

print(f"Report generated: {report_file}")

# --- End of thirteenth block ---

# --- Fourteenth block: Generating frequency report with Gene annotation (using Ensembl REST API) ---
import pandas as pd
import requests

input_file = "combined_cnvs_classificado_detalhado.txt"
report_file = "cnv_frequency_report_with_genes.txt"

df = pd.read_csv(input_file, sep='\t')

# Preprocessing: filter and create SegmentID
# Pré-processamento: filtrar e criar SegmentID
df = df[~df['Chromosome'].isin(['chrM', 'MT', 'M'])]
df['SegmentID'] = df['Chromosome'].astype(str) + ":" + df['Start'].astype(str) + "-" + df['End'].astype(str)

cnv_col = 'CNV_Type_Detalhada'
# Group and calculate frequencies
# Agrupar e calcular frequências
segment_counts = df.groupby(['SegmentID', cnv_col]).size().reset_index(name='Count')
total_samples = segment_counts['Count'].sum()
segment_counts['Frequency_pct'] = (segment_counts['Count'] / total_samples) * 100
top5 = segment_counts.sort_values('Count', ascending=False).head(5)

# Function to query overlapping genes from Ensembl REST API
# Função para consultar genes sobrepostos da API REST do Ensembl
def query_ensembl_genes(chrom, start, end):
    server = "https://rest.ensembl.org"
    ext = f"/overlap/region/human/{chrom}:{start}-{end}?feature=gene"
    headers = {"Content-Type": "application/json"}
    try:
        response = requests.get(server + ext, headers=headers)
        response.raise_for_status()
        genes = response.json()
        # Get symbolic gene names returned
        # Obter nomes simbólicos dos genes retornados
        gene_names = [g.get('external_name', g['id']) for g in genes]
        return ','.join(gene_names) if gene_names else "No gene found" # "Nenhum gene encontrado"
    except Exception as e:
        return f"Query error: {e}" # "Erro na consulta: {e}"

# Placeholder function for querying normative public databases
# Função placeholder para consultar bancos públicos normativos
def query_cnv_frequency_public_db(chrom, start, end):
    # Placeholder for actual query to normative databases like gnomAD/DGV
    # Placeholder para consulta real a bancos normativos como gnomAD/DGV
    return "N/A" # "N/D"

# Function to characterize CNV based on detailed type
# Função para caracterizar CNV
def characterize_cnv(cnv_type):
    ct = cnv_type.lower()
    if 'homozygous deletion' in ct or 'deleção homozigota' in ct:
        return "Complete loss of genetic material" # "Perda completa de material genético"
    elif 'deletion' in ct or 'deleção' in ct:
        return "Partial loss of genetic material" # "Perda parcial de material genético"
    elif 'neutral' in ct or 'neutra' in ct:
        return "No significant alteration" # "Sem alteração significativa"
    elif 'gain' in ct or 'duplication' in ct or 'amplification' in ct:
        return "Copy gain or amplification" # "Ganho de cópias ou amplificação"
    else:
        return "Unknown type" # "Tipo desconhecido"

# Write the expanded report including genes
# Escrever o relatório expandido incluindo genes
with open(report_file, "w") as f:
    f.write("Report of most frequent CNVs, cohort frequency, normative database, genes in regions\n\n")
    # "Relatório CNVs mais frequentes, frequência coorte, banco normativo, genes nas regiões\n\n"
    f.write("SegmentID\tCNV Type\tCohort Count\tCohort Frequency (%)\tNormative Database Frequency (%)\tCharacterization\tGenes\n")
    for idx, row in top5.iterrows():
        chrom = row['SegmentID'].split(':')[0]
        start, end = row['SegmentID'].split(':')[1].split('-')
        freq_coorte = round(row['Frequency_pct'], 2)
        cnv_type = row[cnv_col]
        count_coorte = row['Count']
        freq_pop = query_cnv_frequency_public_db(chrom, start, end)
        characterization = characterize_cnv(cnv_type)
        genes = query_ensembl_genes(chrom, start, end) # Gene annotation query
        f.write(f"{row['SegmentID']}\t{cnv_type}\t{count_coorte}\t{freq_coorte}\t{freq_pop}\t{characterization}\t{genes}\n")

print(f"Expanded report generated: {report_file}")